version: "3.8"

services:
    nova_django_wsgi:
        container_name: nova_django_wsgi
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Docker/Django_WSGI/Dockerfile
        ports: 
            - "8069:8069"
        volumes:
            - ./app:/app
        networks:
            - nova-app-network

    nova_nginx:
        container_name: nova_nginx
        build:
            context: .
            dockerfile: ./Docker/Nginx/Dockerfile
        ports:
          - "9000:9000"
        depends_on:
            - nova_django_wsgi
        volumes:
            - .:/app
        networks:
          - nova-app-network

networks:
  nova-app-network: