name: Deploy

on:
  push:
    branches:
      - app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: login dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Django Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Docker/Django_WSGI/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/image-django-wsgi
      
    - name: Build and push Nginx Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Docker/Nginx/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/image-pycab-nginx

    - name: Copy Docker Compose yml file and Dockerfiles
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.HOST_PASSWORD }}
        port: 22
        source: "docker-compose.yml,Docker"
        target: /home/nova_test_case

    - name: Download Docker-yml file and run containers
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.HOST_PASSWORD }}
        port: 22
        script: |
          cd /home/nova_test_case
          docker compose -f docker-compose.yml pull
          docker compose --env-file=.env -f docker-compose.yml up --build -d
          docker image prune --force
